---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-9.3
  - name: debian-8.10
  - name: centos-7.4
  - name: centos-6.9
  - name: fedora-27
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false
  - name: windows-2012
    driver:
      box: roboticcheese/windows-2012

suites:
  - name: default
    run_list:
      - recipe[x2go-client]
  - name: remove
    run_list:
      - recipe[x2go-client_test::remove]
