---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: debian-8.2
  - name: centos-7.1
  - name: centos-6.7
  - name: fedora-21
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false
  - name: windows-2012
    driver:
      box: roboticcheese/windows-2012
  # TODO: - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[x2go-client]
  - name: remove
    run_list:
      - recipe[x2go-client_test::remove]
