---
driver:
  name: docker
  privileged: true

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8.2
  - name: centos-7
  - name: centos-6
  # TODO: Pending either Chef fixes for DNF in Fedora 22 or a Fedora 21 Docker
  # container with Systemd
  # - name: fedora-22
