language: ruby

branches:
  only:
    - master

sudo: required
services:
  - docker

install:
  - sudo apt-get purge -y lxc-docker
  - wget -qO- https://get.docker.com/ | sudo sh
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle install --without=development integration

before_script:
  # Pending ENV support in Kitchen's Rake tasks and not just the CLI
  - cp .kitchen.travis.yml .kitchen.local.yml

script:
  - chef exec rake && chef exec kitchen test

after_script:

env:
  global:
    # - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
